version: '3'

services:

  dbapi:
    container_name: dbapi
    restart: always
    build: ./dbapi
    volumes: 
      - ./dbapi:/dbapi
      - ./soup.db:/soup.db
    networks:
      - soupnetwork
    expose:
      - "8080"
    ports:
      - "8080:8080"

  webapp:
    container_name: webapp
    restart: always
    build: ./webapp
    volumes: 
      - ./webapp:/webapp
    networks:
      - soupnetwork
    expose:
      - "5000"
    ports:
      - "5000:5000"

  nginx:
    container_name: nginx
    restart: always
    build: ./nginx
    networks:
      - soupnetwork
    expose:
      - "80"
    ports:
      - "80:80"

  ml:
    container_name: ml
    build: ./ml
    networks:
      - soupnetwork

networks:
  soupnetwork:
